name: GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 15
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish
        run: |
          git push origin `git subtree split --prefix public master`:gh-pages --force

      # env:
      #   GITHUB_TOKEN: ${{ secrets.github_token }}
      #   DEPLOY_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
