# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
      
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 15
        cache: 'npm'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build
      
      
      # env:
      #   GITHUB_TOKEN: ${{ secrets.github_token }}
      #   DEPLOY_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}


